### ISSUE TITLE
Woocommerce - Manager can’t received new  order email

### ISSUE THREAD

**Issue by JessicaHuangF23** [ECPay/WooCommerce_Payment#1]
你好
想請問若是訪客選擇「綠界科技」付款後，原本管理者應該要收到的「新訂單」通知信一直未收到。
訪客應收到的「訂購完成」通知信，也未收到，取而代之的卻是收到「新增備註」的通知信。
請問該如何設定或是有何解決方式？

**Comment by JessicaHuangF23** [comment]
我記得「自動回到order-received這個頁面」好像可以從綠界的廠商後台設定。
有可能是因為這個原因，但是我覺得也有可能是安裝的theme衝突綠界科技的外掛...

**Comment by AllennChang** [comment]
感謝您的發問, 若還有使用上的問題, 請寄信到,  techsupport@ecpay.com.tw 有專人為你服務回答, 感謝
