### ISSUE TITLE
請問是否支援 wordpress、WooCommerce 新版本？

### ISSUE THREAD

**Issue by kimisme9386** [ECPay/WooCommerce_Payment#10]
* wordpress 4.9.x
* WooCommerce 3.4.x

請問是否支援呢？

**Comment by AllennChang** [comment]
您好, 感謝你的發問, 目前我們未測試過WooCommerce 3.4.x的版本, 目前已測試過的版本只支援到, WooCommerce 3.2.1 ,若未來有完成最新版程式, 我們會再更新到官網及GITHUB上的說明

**Comment by robert1112** [comment]
@AllennChang  希望可以盡快排入時程！感謝

**Comment by kimisme9386** [comment]
@AllennChang 謝謝回覆，看來大家買 wordpress 版型時，要看清楚是否支援或相容 woocommerce 3.2.x 版，不過有的版型寫有相容，但實際上還是有問題....

**Comment by mike20139631** [comment]
你好 是否有支援WordPress 4.9.8?

**Comment by AllennChang** [comment]
> 你好 是否有支援WordPress 4.9.8?

您好, 經我們內部測試 WordPress 4.9.8 功能上是可以正常使用
