### ISSUE TITLE
WordPress 4.9.8 , WooCommerce 3.5.1 版本詢問

### ISSUE THREAD

**Issue by mike20139631** [ECPay/WooCommerce_Payment#12]
如果版本是這兩個:WordPress 4.9.8 , WooCommerce 3.5.1
1.請問能直接安裝ECPay嗎?(還是不能裝?) 還是說可以裝,但不確定哪邊會有問題?
2. 使用綠界購物車模組,WordPress需要有會員機制的模組嗎?
3. 或是能從哪裡下載到低版本的WooCommerce ?

**Comment by AllennChang** [comment]
WordPress 4.9.8

> 如果版本是這兩個:WordPress 4.9.8 , WooCommerce 3.5.1
> 1.請問能直接安裝ECPay嗎?(還是不能裝?) 還是說可以裝,但不確定哪邊會有問題?
> 2. 使用綠界購物車模組,WordPress需要有會員機制的模組嗎?
> 3. 或是能從哪裡下載到低版本的WooCommerce ?
您好, 感謝您的提問, 回覆如下
1. 可以. 請問有遇到何種問題嗎?
2.不用

**Comment by seanlee1205** [comment]
WooCommerce 3.5.x 按了地圖之後不會有任何反應，不知道有更新的計畫嗎? 手邊的plugin和theme都更新到3.6.x了，就等綠界更新了

**Comment by AllennChang** [comment]
> WooCommerce 3.5.x 按了地圖之後不會有任何反應，不知道有更新的計畫嗎? 手邊的plugin和theme都更新到3.6.x了，就等綠界更新了

您好, 感謝您的反應,  
1.目前我們已有安排更新的開發計劃,待完成後會更新在這裡 
2.若目前使用WooCommerce 3.5.x 按了地圖之後不會有任何反應,請協助降版到我們有支援的版本

**Comment by AllennChang** [comment]
您好, 最新版已支援到3.6.4 ,若有任何問題, 歡迎再跟我們回報, 感謝
