### ISSUE TITLE
銀聯卡輸入大陸手機號碼問題

### ISSUE THREAD

**Issue by gralance** [ECPay/WooCommerce_Payment#15]
幫朋友架站, 已使用  WooCommerce + ecpay 運作一段時間
最近有大陸人嘗試想用銀聯卡刷卡購買, 綠界的刷卡界面要求輸入手機號碼, 但是大陸手機號碼的
輸入格式不被接受, 請問該如何讓大陸人也能順利刷卡呢？

**Comment by AllennChang** [comment]
您好, 感謝您的詢問, 目前綠界有支援海外手機號碼, 請在手機號碼前加上國碼即可, 若有任何問題,請再跟我們反應, 感謝您

**Comment by gralance** [comment]
收到, 感謝
