### ISSUE TITLE
版本1.3門市取資料issue

### ISSUE THREAD

**Issue by brian1318** [ECPay/WooCommerce_Payment#17]
請問一下，user選取超商門市後，返回商店後，卻無超商門市資訊，可能的問題會是什麼呢？

**Comment by AllennChang** [comment]
您好, 感謝你的發問, 
我們經測試在官方原生模組下沒有遇到這樣的問題，
還請一一停用使用的外掛或佈景主題，以釐清是哪部分造成綠界模組異常，
或另安裝一原生購物車進行測試，待測試無誤才安裝他方外掛模組。

**Comment by brian1318** [comment]
首先感謝回覆，是我的checkout page程式中mapping fields 的問題，已修正完成。打擾了，再次感謝百忙中撥空回覆！
