### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by andyliuonline** [ECPay/WooCommerce_Payment#19]
![截圖 2020-06-03 21 31 38](https://user-images.githubusercontent.com/34826012/83644534-f97b7b80-a5e3-11ea-8560-bd2160bfde59.png)

安裝在 Wordpress 5.4.1 時，啟用外掛後，會出現圖片中說明的問題

**Comment by adelachang0418** [comment]
您好, 開發團隊需要您提供下列資訊, 請再幫忙,感謝
購物車版本：
*模組版本：
*PHP 版本：
*重現方式：
若有使用 Plugin 請提供名稱與版本:

**Comment by tjliu912** [comment]
購物車版本：4.2.0
*模組版本：ECPay Payment for WooCommerce 1.2.2003020
*PHP 版本：7.4
*重現方式：Wordpress 5.4.1

**Comment by adelachang0418** [comment]
您好
目前我們尚未支援Wordpress 5.4,會請開發團隊安排研發, 未來釋出新版後再請客戶套用
現階段建議參考模組支援的版本使用
感謝
