### ISSUE TITLE
對 WooCommerce 4.2 compatibility / 相容性

### ISSUE THREAD

**Issue by MGdesigner** [ECPay/WooCommerce_Payment#20]
WooCommerce 最新版已經更新到 4.2 版。 WooCommerce 回報說 "ECPay Payment for WooCommerce " 只有支援到  WooCommerce 3.9.2，需要更新。

**Comment by AllennChang** [comment]
您好, 您的需求, 我已反應給開發團隊, 他們會在安排時間進行研發, 感謝您的反應 ,

**Comment by AllennChang** [comment]
您好, 目前已支援到4.2版, 若有任何問題,歡迎再跟我們反應, 感謝
