### ISSUE TITLE
可否後台自訂啟用 OrderResultURL

### ISSUE THREAD

**Issue by hirakujira** [ECPay/WooCommerce_Payment#21]
您好，想請問是否可以新增一個選項讓後台使用 OrderResultURL？
或者直接打勾讓 OrderResultURL 直接使用 ClientBackURL 也可以，因為想要讓使用者付款完畢之後直接導向商店頁面，不用再按跳轉...謝謝

**Comment by AllennChang** [comment]
您好, 您的問題我們已收到, 會跟相關產品經理反應您的問題, 感謝您的反應
