### ISSUE TITLE
訂單選擇 ATM 付款未過期限提前被取消訂單

### ISSUE THREAD

**Issue by speshiou** [ECPay/WooCommerce_Payment#25]
*購物車版本：WooCommerce 4.9
*模組版本：ECPay v1.2.2003020
*瀏覽器版本：Chrome 86
*PHP 版本：7.3
*問題描述：
付款截止日 : 2021/04/11，但2021-04-08 於 1:50 下午就被通知付款期限已過，訂單狀態變更為取消，等於不到三小時就被取消。

以下為訂單原始備註的記錄：

未付款訂單已取消 – 付款期限已過。 訂單狀態由 等待付款中 變更為 取消.
2021-04-08 於 1:50 下午 刪除備註

付款方式 : ATM_CHINATRUST
付款時間 : 2021/04/08 10:57:47
銀行代碼 : 822
虛擬帳號 : 9829411019605745
付款截止日 : 2021/04/11
取號結果 : (2)Get VirtualAccount Succeeded
2021-04-08 於 10:57 上午 刪除備註

ATM
2021-04-08 於 10:57 上午 刪除備註

*重現方式：
1. 訂購任何商品
2. 結帳選擇 ATM 付款
3. 不進行匯款
4. 幾小時後查看，訂單已被取消

*其它套件說明：
無

**Comment by adelachang0418** [comment]
您好,
可能是W庫存管理機制取消所導致, 再麻煩至後台設定確認是否有問題
請參考以下網址:
https://www.webtoffee.com/woocommerce-order-cancelled-after-successful-paypal-payment-unpaid-order-cancelled-time-limit-reached/

有任何問題再隨時與我們聯絡
感謝

**Comment by speshiou** [comment]
測試過後，確實是保留庫存的設定的期限較短的問題，感謝。
