### ISSUE TITLE
貨幣無法跟woocommerce同步

### ISSUE THREAD

**Issue by woei66** [ECPay/WooCommerce_Payment#26]
wordpress 版本 5.7.2
woocommerce 版本5.3.0
ECPay Payment for WooCommerce版本 2.0.2104150
我在wooCommerce設定商品價格為美金300元,
結帳時, 到ecpay用信用卡結帳時, 變成新台幣 300元

**Comment by AllennChang** [comment]
@woei66  您好,感謝你的提問, 抱歉目前ecpay 不支援外幣交易,只有支援新台幣, 若要使用ecpay 時需把商品設成新台幣的價格結帳
 若有任何使用上問題,歡迎再跟我們反應, 感謝您
