### ISSUE TITLE
【急】接收綠界付款結果出現No CheckMacValue parameter的錯誤訊息

### ISSUE THREAD

**Issue by amylin22** [ECPay/WooCommerce_Payment#30]
我們是用C#的方式撰寫，有載入綠界提供的DLL檔，
也使用綠界提供的測試特店資料，
撰寫方式也是以綠界所提供的範例程式所撰寫
在不同的專案用同樣的方式，一個專案卻會出現錯誤訊息是No CheckMacValue parameter
想確認一下可能的原因是甚麼?
因為看過DLL裡的程式，檢查碼的產生與比對都是由綠界DLL裡執行的..
感謝幫忙~!!

**Comment by AllennChang** [comment]
您好, 為了方便查詢問題, 請幫忙寫信到, techsupport@ecpay.com.tw 我們將專員為您們服務, 
來信請提供交易時間, 交易編號, 及串接使用的特店編號及串接網址, 感謝您
