### ISSUE TITLE
[新功能]將ATM繳款資料寫入後台和返回的訂單確認頁

### ISSUE THREAD

**Issue by robert1112** [ECPay/WooCommerce_Payment#4]
您好

使用ＡＴＭ取號後，是否可以將「ATM繳款資料」寫入「後台訂單頁面」和「返回的訂單確認頁」，讓店家和消費者都能去看知道什麼時候付款，感覺是很基本，很直覺的需求！希望可以考慮整合進來。

感謝您們～

```
訂單金額
1,080 元 
付款方式	ATM 櫃員機
銀行代碼	012
ATM繳費帳號	3243434343434232
繳費截止日期	2018/04/27 23:59:59
```

**Comment by AllennChang** [comment]
你好, 請跟我們技術客服團隊連絡,將安排專員協助服務您的問題, 請寄信到 techsupport@ecpay.com.tw ,再麻煩囉
