### ISSUE TITLE
請問測試模式是否異常?還是我的設定有問題呢?

### ISSUE THREAD

**Issue by eric2100** [ECPay/WooCommerce_Payment#5]
測試模式 啟用

就會發生
交易失敗！
商店尚未開啟收款服務，請聯繫商店處理
返回商店
1.商店尚未開啟收款服務。
2.交易金額低於下限或超過上限。
3.此商店未提供任何付款方式。
4.建議您先與購買商品的商家或購物網站業者聯繫！

若非以上原因，請電洽綠界客服中心，我們將協助處理您的問題，謝謝！

**Comment by AllennChang** [comment]
已回覆, 請再收信, 感謝

**Comment by eric2100** [comment]
謝謝回復，目前已經正常了，非常謝謝。

**Comment by robert1112** [comment]
@eric2100  @AllennChang  您好，我有同樣問題！該怎麼解決呢？感謝您～

**Comment by AllennChang** [comment]
@robert1112  請提供您的mail 我回覆給您

**Comment by robert1112** [comment]
tradecross at outlook dot com Thank you @AllennChang

**Comment by AllennChang** [comment]
tradecross@outlook.com ?

**Comment by robert1112** [comment]
yes @AllennChang

**Comment by sos50124** [comment]
你好 我也有相同問題,請問該如何解決呢? 謝謝!! 
我的信箱:sos50124@gmail.com

**Comment by AllennChang** [comment]
感謝您反應問題, 已回覆,

**Comment by lucas7512** [comment]
@AllennChang 您好，我也有相同問題想請教
我的信箱:lucifer_mx@hotmail.com

**Comment by AllennChang** [comment]
@lucas7512  感謝您反應問題, 已回覆

**Comment by jhangling** [comment]
您好，也遇到同樣問題，想知道如何解決，是否可以麻煩您也提供給我呢？
我的信箱：jhangling46@gmail.com
謝謝您！

**Comment by rockylhc** [comment]
我測試環境也有一樣的問題，請問如何解決呢？
rockylhc@hotmail.com 謝謝!

**Comment by papergenkio** [comment]
你好：我也有相同問題
paperkeropa@gmail.com

**Comment by pennyweng** [comment]
您好，我也有相同問題
penny.weng@gmail.com

**Comment by AllennChang** [comment]
@papergenkio  @pennyweng  感謝您們反應, 已回覆

**Comment by a-ken** [comment]
有相同問題，為什麼不直接在 issue 回覆?
aken1104@gmail.com

**Comment by ttt0952** [comment]
Hello @AllennChang 我在從測試環境切回正式環境後也遇到相同問題，請問是什麼問題呢？
我的信箱是ttt0952@gmail.com，感謝您！

**Comment by asd7333477** [comment]
您好，我也有相同問題
T40314125@go.meiho.edu.tw

**Comment by AllennChang** [comment]
「商店尚未開啟收款服務，請聯繫商店處理」錯誤訊息是以下情境導致的，煩請確認，謝謝。

1.	若串接正式環境會員編號，在購物車後台設定點選測試模式，會導致上述情況，煩請將測試模式為空值

2.	若您想先使用測試環境進行測試，請改用測試帳號及HASH KEY & IV並勾選測試模式

**Comment by asd7333477** [comment]
> 「商店尚未開啟收款服務，請聯繫商店處理」錯誤訊息是以下情境導致的，煩請確認，謝謝。
> 
> 1. 若串接正式環境會員編號，在購物車後台設定點選擇測試模式，會導致上述情況，煩惱測試模式為空值
> 2. 若您想先使用測試環境進行測試，請改用測試帳號及HASH KEY＆IV和切換測試模式

您好，謝謝您這麼快給我答覆。我的綠界後台沒有顯示測試模式，是直接用後台的HASH KEY＆IV串到All In One中，請問這樣可以看出是哪邊出了問題嗎?

**Comment by AllennChang** [comment]
感謝您反應問題, 已回覆,

**Comment by shooding** [comment]
同上 我的綠界後台沒有顯示測試模式，是直接用後台的HASH KEY＆IV串到  sample_WebATM_CreateOrder.php

訊息代碼 Message code：10200141
訊息說明 Description：商店尚未提供任何付款方式，請聯繫商店處理。

shooding@gmail.com

**Comment by AllennChang** [comment]
您好, 請幫忙寫信到techsupport@ecpay.com.tw ,我們會有專人協助回覆, 感謝

**Comment by shooding** [comment]
> 同上 我的綠界後台沒有顯示測試模式，是直接用後台的HASH KEY＆IV串到 sample_WebATM_CreateOrder.php
> 
> 訊息代碼 Message code：10200141
> 訊息說明 Description：商店尚未提供任何付款方式，請聯繫商店處理。
> 
> [shooding@gmail.com](mailto:shooding@gmail.com)

抱歉自問自答找到解法了。文件中有提到, 然後把Sample code換成正式服務位置：

// $obj->ServiceURL  = "https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5"; //測試服務位置
    $obj->ServiceURL  = "https://payment.ecpay.com.tw/Cashier/AioCheckOut/V5"; //正式服務位置

**Comment by itj205** [comment]
你好，
測試模式和正常錯誤10200073

WordPress & ECPay Plugin
https://wordpress.org/plugins/ecpay-payment-for-woocommerce/

交易失敗 Transaction failed

訊息代碼 Message code：10200073
訊息說明 Note for message：CheckMacValue Error.

常見失敗原因如下 Frequently seen causes for failure as below

商店尚未開啟收款服務，請聯繫商店處理。 The merchant has not activated payment collection service.
交易金額低於下限或超過上限
Transaction is less than lower limit or more than upper limit.
此商店未提供任何付款方式，請聯繫商店處理。 The store does not provide any payment method. Please contact the merchant.
此商店所傳送串接參數錯誤，請聯繫商店處理。 Incorrect parameter. Please contact the merchant.
建議您先與購買商品的商家或購物網站業者聯繫 Suggest contact with seller of the merchandize or online shop first!
若您的問題非以上原因，請洽綠界客服中心，我們將協助處理您所遇到的問題。
Please contact ECPay customer service if you have checked and confirmed the above issues do not exist. We will assist you with the problem.

**Comment by itj205** [comment]
你好我正在測試付款連結，但是一直出現以下訊息“

“訊息代碼 Message code：10200073”   

‘商店尚未開啟收款服務，請聯繫商店處理。

交易金額低於下限或超過上限此商店未提供任何付款方式，請聯繫商店處理。 

此商店所傳送串接參數錯誤，請聯繫商店處理。 

建議您先與購買商品的商家或購物網站業者聯繫 !

**Comment by itj205** [comment]
你好我正在測試付款連結，但是一直出現以下訊息“

“訊息代碼 Message code：10200073”   
‘商店尚未開啟收款服務，請聯繫商店處理。
交易金額低於下限或超過上限此商店未提供任何付款方式，請聯繫商店處理。 
此商店所傳送串接參數錯誤，請聯繫商店處理。 

請問該如何解決這問題？？？

**Comment by adelachang0418** [comment]
您好
您的 hashkey 跟 hashIV 商店代號只能用於正式環境
再麻煩嘗試切換至正式環境
有問題在隨時與我們聯絡
謝謝

**Comment by hanaskuliah** [comment]
我也有相同問題,請問該如何解決呢? 謝謝!!

常見失敗原因如下 Frequently seen causes for failure as below</p>
                                <ul>
                                    <li>
                                        <p>商店尚未開啟收款服務，請聯繫商店處理。 The merchant has not activated payment collection service.</p>
                                    </li>
                                    <li>
                                        <p>交易金額低於下限或超過上限
                                            <br/>Transaction is less than lower limit or more than upper limit.
                                        </p>
                                    </li>
                                    <li>
                                        <p>此商店未提供任何付款方式，請聯繫商店處理。 The store does not provide any payment method. Please contact the merchant.</p>
                                    </li>
                                    <li>
                                        <p>此商店所傳送串接參數錯誤，請聯繫商店處理。 Incorrect parameter. Please contact the merchant.</p>
                                    </li>
                                    <li>
                                        <p>建議您先與購買商品的商家或購物網站業者聯繫 Suggest contact with seller of the merchandize or online shop first!</p>
                                    </li>

我的信箱:hanaskuliah@gmail.com

**Comment by AllennChang** [comment]
@hanaskuliah 感謝您反應問題, 已回覆,

**Comment by albertwow80** [comment]
您好,

目前串接了綠界API，也輸入了KEY，結帳時出線Error code
訊息代碼 Message code：10300023
訊息說明 Note for message：本次交易未提供任何付款方式，請與商店聯繫確認。

我的信箱:albertwow80@gmail.com

謝謝您

**Comment by tsou8599** [comment]
您好,

目前串接了綠界API，也輸入了KEY，結帳時出線Error code
訊息代碼 Message code：10300023
訊息說明 Note for message：本次交易未提供任何付款方式，請與商店聯繫確認。

我的信箱:tsou8599@gmail.com

謝謝您

**Comment by AllennChang** [comment]
> 您好,
> 
> 目前串接了綠界API，也輸入了KEY，結帳時出線Error code
> 訊息代碼 Message code：10300023
> 訊息說明 Note for message：本次交易未提供任何付款方式，請與商店聯繫確認。
> 
> 我的信箱:[albertwow80@gmail.com](mailto:albertwow80@gmail.com)
> 
> 謝謝您

您好請參考下列網址說明
https://www.ecpay.com.tw/CascadeFAQ/CascadeFAQ_Qa?nID=1477

**Comment by AllennChang** [comment]
> 您好,
> 
> 目前串接了綠界API，也輸入了KEY，結帳時出線Error code
> 訊息代碼 Message code：10300023
> 訊息說明 Note for message：本次交易未提供任何付款方式，請與商店聯繫確認。
> 
> 我的信箱:[tsou8599@gmail.com](mailto:tsou8599@gmail.com)
> 
> 謝謝您

您好請參考下列網址說明
https://www.ecpay.com.tw/CascadeFAQ/CascadeFAQ_Qa?nID=1477

**Comment by devadev2485** [comment]
> Replied, please re-receive, thanks

 I have the same problem in laravel 

訊息代碼 Message code：10200073
訊息說明 Note for message：CheckMacValue Error.

please help me 
My email: bdeva121@gmail.com

**Comment by AllennChang** [comment]
> > Replied, please re-receive, thanks
> 
> I have the same problem in laravel
> 
> 訊息代碼 Message code：10200073
> 訊息說明 Note for message：CheckMacValue Error.
> 
> please help me
> My email: [bdeva121@gmail.com](mailto:bdeva121@gmail.com)

您好,請參考以下連結說明, 若還有任何問題, 歡迎再跟我們連絡, 感謝
https://www.ecpay.com.tw/CascadeFAQ/CascadeFAQ_Qa?nID=1197

**Comment by xxxhand** [comment]
你好：

我這邊也遇到相同問題，已參考FAQ連結無解，還請幫忙

訊息代碼 Message code：10200073
訊息說明 Note for message：CheckMacValue Error.

我的信箱：nohandboy@gmail.com

還請回覆，謝謝。

**Comment by AllennChang** [comment]
> 你好：
> 
> 我這邊也遇到相同問題，已參考FAQ連結無解，還請幫忙
> 
> 訊息代碼 Message code：10200073
> 訊息說明 Note for message：CheckMacValue Error.
> 
> 我的信箱：[nohandboy@gmail.com](mailto:nohandboy@gmail.com)
> 
> 還請回覆，謝謝。

您好,請參考以下連結說明, 若還有任何問題, 歡迎再跟我們連絡, 感謝
https://www.ecpay.com.tw/CascadeFAQ/CascadeFAQ_Qa?nID=1197

**Comment by AllennChang** [comment]
> 你好：
> 
> 我這邊也遇到相同問題，已參考FAQ連結無解，還請幫忙
> 
> 訊息代碼 Message code：10200073
> 訊息說明 Note for message：CheckMacValue Error.
> 
> 我的信箱：[nohandboy@gmail.com](mailto:nohandboy@gmail.com)
> 
> 還請回覆，謝謝。

已mail 回覆, 若有任何問題,請再跟我們連絡, 感謝

**Comment by northleo561** [comment]
您好，

先前綠界已使用超過2年，但是這2天信用卡結帳時出現錯誤

訊息代碼 Message code：10200141
訊息說明 Note for message：商店尚未提供任何付款方式，請聯繫商店處理。

我的信箱：jddt226@gmail.com

謝謝您

**Comment by a4687b** [comment]
你好：

我這邊也遇到相同問題，已參考FAQ連結無解，還請幫忙

訊息代碼 Message code：10100066
訊息說明 Note for message：TradeDesc Is Null

我的信箱：a4687b@gmail.com

還請回覆，謝謝。

**Comment by WEYU45577** [comment]
我也是測試金流
交易失敗，訊息代碼是10100066


把測試模組取消，錯誤代碼變10200141

訊息代碼 Message code：10200141
訊息說明 Description：商店尚未提供任何付款方式，請聯繫商店處理。

請求協助><

s102001348@gmail.com

**Comment by wuchienhsun** [comment]
你好：

我這邊也遇到相同問題，已參考FAQ連結無解，還請幫忙

訊息代碼 Message code：10200073
訊息說明 Note for message：CheckMacValue Error.

我的信箱：wuchienhsun01@gmail.com

還請回覆，謝謝。
