### ISSUE TITLE
訂單付款成功後會自動取消

### ISSUE THREAD

**Issue by tim90403** [ECPay/WooCommerce_Payment#6]
問題簡介如下：
1. 客戶使用ATM付款後，交易成功，狀態由尚未付款改為已付款
2. 然後訂單過了一段時間，跳出The order already paid or not in the standard procedure訊息，然後訂單狀態自動變為失敗
3. 手動將訂單狀態由失敗變為處理中，結果一樣跳出前述訊息，又將狀態改為失敗
4. 經過查證，這段訊息是來自於貴公司的程式碼，位置為ecpay/includes/class-wc-gateway-ecpay.php
第327行

以下附上訂單的備註紀錄(越上面越新)：
--
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:16
付款失敗
錯誤訊息 : The order already paid or not in the standard procedure 1435.
訂單狀態由 處理中 變更為 失敗.

新增於 2018-06-07 1:11 上午 刪除備註
--
訂單狀態由 失敗 變更為 處理中.

新增於 2018-06-06 10:20 下午 由 hosin	刪除備註
--
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:16
付款失敗
錯誤訊息 : The order already paid or not in the standard procedure 1435.
訂單狀態由 處理中 變更為 失敗.

新增於 2018-06-06 1:07 下午 刪除備註
--
訂單狀態由 等待付款中 變更為 處理中.

新增於 2018-06-06 1:00 下午 刪除備註
--
Booking #1433 status changed from “尚未付款” to “已付款”

新增於 2018-06-06 1:00 下午 刪除備註
--
付款結果 : (1)交易成功

新增於 2018-06-06 1:00 下午 刪除備註
--
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:54
銀行代碼 : 812
虛擬帳號 : 9567770928671609
付款截止日 : 2018/06/09
取號結果 : (2)Get VirtualAccount Succeeded

新增於 2018-06-06 12:37 下午 刪除備註
--
ATM

新增於 2018-06-06 12:37 下午 刪除備註
--
Booking #1433 status changed from “購物車” to “尚未付款”

新增於 2018-06-06 12:37 下午 刪除備註
--
Booking #1433 status changed from “購物車” to “尚未付款”

新增於 2018-06-06 12:37 下午 刪除備註

**Comment by AllennChang** [comment]
你好 請您把問題反應到, gwtechsupport@ecpay.com.tw ,我們會有專業技術團隊協助您們, 感謝

**Comment by tim90403** [comment]
您好，在此想要反映一個問題，相關問題也同步在GitHub以及WordPress.org裡面
問題簡介如下：
1. 客戶使用ATM付款後，交易成功，狀態由尚未付款改為已付款
2. 然後訂單過了一段時間，跳出The order already paid or not in the standard procedure訊息，然後訂單狀態自動變為失敗
3. 手動將訂單狀態由失敗變為處理中，結果一樣跳出前述訊息，又將狀態改為失敗
4. 經過查證，這段訊息是來自於貴公司的程式碼，位置為ecpay/includes/class-wc-gateway-ecpay.php
第327行
以下附上訂單的備註紀錄(越上面越新)：
—
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:16
付款失敗
錯誤訊息 : The order already paid or not in the standard procedure 1435.
訂單狀態由 處理中 變更為 失敗.
新增於 2018-06-07 1:11 上午 刪除備註
—
訂單狀態由 失敗 變更為 處理中.
新增於 2018-06-06 10:20 下午 由 hosin 刪除備註
—
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:16
付款失敗
錯誤訊息 : The order already paid or not in the standard procedure 1435.
訂單狀態由 處理中 變更為 失敗.
新增於 2018-06-06 1:07 下午 刪除備註
—
訂單狀態由 等待付款中 變更為 處理中.
新增於 2018-06-06 1:00 下午 刪除備註
—
Booking 1433 status changed from “尚未付款” to “已付款”
新增於 2018-06-06 1:00 下午 刪除備註
—
付款結果 : (1)交易成功
新增於 2018-06-06 1:00 下午 刪除備註
—
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:54
銀行代碼 : 812
虛擬帳號 : 9567770928671609
付款截止日 : 2018/06/09
取號結果 : (2)Get VirtualAccount Succeeded
新增於 2018-06-06 12:37 下午 刪除備註
—
ATM
新增於 2018-06-06 12:37 下午 刪除備註
—
Booking 1433 status changed from “購物車” to “尚未付款”
新增於 2018-06-06 12:37 下午 刪除備註
—
Booking 1433 status changed from “購物車” to “尚未付款”
新增於 2018-06-06 12:37 下午 刪除備註

**Comment by tim90403** [comment]
你好，這個信箱似乎無法收信，再麻煩協助確認一下狀況

**Comment by AllennChang** [comment]
techsupport@ecpay.com.tw 不好意思. 更正

**Comment by tim90403** [comment]
您好，在此想要反映一下關於WooCommerce的外掛問題
版本號為180503

問題簡介如下：
1. 客戶使用ATM付款後，交易成功，狀態由尚未付款改為已付款
2. 然後訂單過了一段時間，跳出The order already paid or not in the standard procedure訊息，然後訂單狀態自動變為失敗
3. 手動將訂單狀態由失敗變為處理中，結果一樣跳出前述訊息，又將狀態改為失敗
4. 經過查證，這段訊息是來自於貴公司的程式碼，位置為ecpay/includes/class-wc-gateway-ecpay.php
第327行
以下附上訂單的備註紀錄(越上面越新)：
—
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:16
付款失敗
錯誤訊息 : The order already paid or not in the standard procedure 1435.
訂單狀態由 處理中 變更為 失敗.
新增於 2018-06-07 1:11 上午 刪除備註
—
訂單狀態由 失敗 變更為 處理中.
新增於 2018-06-06 10:20 下午 由 hosin 刪除備註
—
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:16
付款失敗
錯誤訊息 : The order already paid or not in the standard procedure 1435.
訂單狀態由 處理中 變更為 失敗.
新增於 2018-06-06 1:07 下午 刪除備註
—
訂單狀態由 等待付款中 變更為 處理中.
新增於 2018-06-06 1:00 下午 刪除備註
—
Booking 1433 status changed from “尚未付款” to “已付款”
新增於 2018-06-06 1:00 下午 刪除備註
—
付款結果 : (1)交易成功
新增於 2018-06-06 1:00 下午 刪除備註
—
付款方式 : ATM_TAISHIN
付款時間 : 2018/06/06 12:37:54
銀行代碼 : 812
虛擬帳號 : 9567770928671609
付款截止日 : 2018/06/09
取號結果 : (2)Get VirtualAccount Succeeded
新增於 2018-06-06 12:37 下午 刪除備註
—
ATM
新增於 2018-06-06 12:37 下午 刪除備註
—
Booking 1433 status changed from “購物車” to “尚未付款”
新增於 2018-06-06 12:37 下午 刪除備註
—
Booking 1433 status changed from “購物車” to “尚未付款”
新增於 2018-06-06 12:37 下午 刪除備註

**Comment by tim90403** [comment]
Dear:


感謝您的來信，已將此問題的產生並反應給相關單位協助，

此專案為 32007，由於優化尚需時日，

若您急需避免此情況發生，請先刪除目前使用的模組，

再安裝下載前一版安裝使用(連結如下)，

https://github.com/ECPay/WooCommerce_Payment/releases/tag/v1.1.180313

另外提醒您 因不清楚貴司網站架構及套件的相容性，

建議您先備份網站，再安裝確認，造成不便還請見諒，謝謝。





Tks.
BR
綠界科技 - 技術支援窗口 11
=================================================
綠界科技股份有限公司
Green World FinTech Service Co., Ltd.
台北市南港區三重路19-2號6樓 , D棟
E-mail:techsupport@ecpay.com.tw
=================================================

**Comment by tim90403** [comment]
Dear:


感謝耐心等候，此專案目前已優化完成，

提供套件載點，給您參考。

https://github.com/ECPay/WooCommerce_Payment/blob/master/ecpay.zip

提醒您因不清楚貴司網站架構及套件的相容性，

建議您先備份網站，再安裝更新確認，謝謝。




感謝您的來信

Tks.
BR
綠界科技 - 技術支援窗口 11
=================================================
綠界科技股份有限公司
Green World FinTech Service Co., Ltd.
台北市南港區三重路19-2號6樓 , D棟
E-mail:techsupport@ecpay.com.tw
=================================================

From: gwtechsupport
Sent: Thursday, June 07, 2018 2:18 PM
To: 嚴天郁; ECPay/WooCommerce_Payment; gwtechsupport
Cc: ECPay/WooCommerce_Payment; Author
Subject: RE: [ECPay/WooCommerce_Payment] 訂單付款成功後會自動取消 (#6)

Dear:


感謝您的來信，已將此問題的產生並反應給相關單位協助，

此專案為 32007，由於優化尚需時日，

若您急需避免此情況發生，請先刪除目前使用的模組，

再安裝下載前一版安裝使用(連結如下)，

https://github.com/ECPay/WooCommerce_Payment/releases/tag/v1.1.180313

另外提醒您 因不清楚貴司網站架構及套件的相容性，

建議您先備份網站，再安裝確認，造成不便還請見諒，謝謝。





Tks.
BR
綠界科技 - 技術支援窗口 11
=================================================
綠界科技股份有限公司
Green World FinTech Service Co., Ltd.
台北市南港區三重路19-2號6樓 , D棟
E-mail:techsupport@ecpay.com.tw
=================================================

**Comment by tim90403** [comment]
大約三天前還是接到顧客反映，狀況一樣，訂單會自動取消，若需要協助建立一個複製版本的網站，再麻煩說一聲，可以拿來進行測試

**Comment by AllennChang** [comment]
您好, 我們最新版本已修正這個問題囉, https://github.com/ECPay/WooCommerce_Payment/releases/tag/V1.1.180528
若有任何問題,請再反應
techsupport@ecpay.com.tw 信箱
