### ISSUE TITLE
交易失敗！CheckMacValue Error.

### ISSUE THREAD

**Issue by robert1112** [ECPay/WooCommerce_Payment#7]
您好

顧客和我自己使用ＡＴＭ付款，但是兩三次都出現「交易失敗！CheckMacValue Error.」，網址是`https://payment.ecpay.com.tw/Cashier/AioCheckOut`

```
WooCommerce version: 3.4.4
ECPay Invoice for WooCommerce by Green World FinTech Service Co., Ltd. – 1.1.180315 –
ECPay Logistics for WooCommerce by ECPay Green World FinTech Service Co., Ltd. – 1.2.180626
WooCommerce ECPay Payment by ECPay Green World FinTech Service Co., Ltd. – 1.1.180528
```

是版本不相容嗎？有解嗎？感謝您

**Comment by AllennChang** [comment]
請check 串接網址
正式環境：https://payment.ecpay.com.tw/Cashier/AioCheckOut/V5

**Comment by robert1112** [comment]
請問改怎麼做呢？感謝您

**Comment by AllennChang** [comment]
請提供你的問題,訂單編號,MID 到 gwtechsupport@ecpay.com.tw 技術客服信箱, , 我們查一下LOG記錄

**Comment by robert1112** [comment]
MID 商店代號	嗎？ 已經寄出囉！再麻煩您們幫忙盡快處理，感謝您！

**Comment by robert1112** [comment]
將在class-wc-gateway-ecpay.php內**_所有_**的`https://payment.ecpay.com.tw/Cashier/AioCheckOut`
改成`https://payment.ecpay.com.tw/Cashier/AioCheckOut/V5` 嗎？

**Comment by AllennChang** [comment]
不好意思. 請問我們技術客服團隊未能解答你的問題嗎?

**Comment by robert1112** [comment]
就是等你們更新模組或我降WC版本，你們目前適用WC版本是去年10月了😳

**Comment by robert1112** [comment]
兼容 WooCommerce version: 3.4.4 
移除特定外掛後，已正常使用 感謝您們
