### ISSUE TITLE
ATM和信用卡付款後，強制跳回「WC完成結帳頁」

### ISSUE THREAD

**Issue by robert1112** [ECPay/WooCommerce_Payment#8]
您好

建議：ATM和信用卡付款後，強制跳回「WC完成結帳頁」
原因：店家在做像素追蹤時，只有在URL符合時才會觸發
目前狀況：ATM取號後，顧客可以選擇是否回到商店。信用卡可能要再確認！

感謝您們

**Comment by AllennChang** [comment]
您好, 感謝您的建議
經評估後  建議貴司可以自行使用ClientRedirectURL 參數,取號完成後即會導回「WC完成結帳頁」
