### ISSUE TITLE
使用測試狀態付款後狀態仍然是等待付款中

### ISSUE THREAD

**Issue by housemeow** [ECPay/WooCommerce_Payment#9]
目前的版本
![image](https://user-images.githubusercontent.com/1990837/45173641-6315fc80-b23b-11e8-9473-5b8a8356c5fb.png)

**Comment by robert1112** [comment]
@housemeow  建議先把其他外掛先暫時使用，在測試看看。

**Comment by housemeow** [comment]
目前是全新的wordpress, 沒有其他外掛

**Comment by AllennChang** [comment]
@housemeow  歡迎來信到techsupport@ecpay.com.tw , 我們會有專人為你服務
